version: '3'

services:
    app:
        build: .
        env_file:
            - .env
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        restart: always

    db:
        image: postgres
        container_name: postgres_go
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data:
